// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doaaarwdaayioxjnedpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvYWFhcndkYWF5aW94am5lZHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyODg1MzksImV4cCI6MjA4Nzg2NDUzOX0.5YUw2Qtg7aR4upAlYi5T4DyHEBQtJuUCIQZDzV4UEwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});